export const PageRoutes = {
  NotFound: '*',
  Forbidden: '/forbidden',
  Home: '/',
  Login: '/',
  Verify: '/auth/verify',
  Game: '/spil',
  Deposit: '/indbetal',
  DepositHistory: '/indbetal/historik',
  Contact: '/kontakt',
  Boards: '/boards',
  Admin: '/admin',
  AdminUsers: '/admin/users',
  AdminGame: '/admin/game/',
  AdminGameHistory: '/admin/game/history',
  AdminDeposits: '/admin/deposits',
} as const;
